mongo: {}
documentdb:
  database: treeherder-proxy

treeherder:
  apiUrl: https://treeherder.mozilla.org/api/

treeherderActions:
  routePrefix: taskcluster
  prefetch: 200

taskcluster:
  credentials: {}

treeherderTaskcluster:
  routePrefix: tc-treeherder
  prefetch: 200

treeherderProxy:
  port: 60025

redis: {}
pulse: {}

kue:
  logFailedJobs: false
  admin:
    port: 60024

repositoryMonitor:
  interval: 60000
  maxPushFetches: 200

commitPublisher:
  title: |
    Pushlog Commit Events
  description: |
    The pushlog events can be used to hook various other components into
    the act of commiting to a particuar repository (usually to kick off tests)
    this exchange is hopefuly a short lived thing which abstracts polling the
    pushlog for new data.

    Pushes will be monitored (via polling) and events will be sent as new data
    is available. If for some reason the service goes down previous commits
    will also be fetched and any missing data (up to a particular amount) will
    be sent as events...

# Nobody's quite sure why this is called try.  Don't be confused!  It includes all
# projects, not just try.
try:
  enabled: true
  # Default url used when figuring out where to fetch task graph has some special
  # mustache parameters used to customize the path.
  #
  #   - alias: current key name
  #   - revision: revision of the change
  #   - path: sub path to repository
  #   - host: host of repository
  #
  defaultUrl: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"

  # If for some reason the task yaml is invalid we still would like to create a
  # task if for no other reason then to notify the user that this failed.
  # XXX: This url is temporary until a real one hits mozilla-central.
  errorTaskUrl: "https://gist.githubusercontent.com/gregarndt/8fc123be2408180c2f13/raw/d12f500faa334bc72cb1dd033e028773ac2476c8/error.yml"

  # Each project can have
  #  - url: url of the decision task YAML (defaults to defaultUrl)
  #  - scopes: scopes for the task graph
  #  - level: SCM level (defaults to 1) passed to the decision task
  projects:
    # Try is unique in that it parses the commit message
    try: # Note the keys match the "alias" which treeherder defines.
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/try.yml"
      level: 1
      scopes:
        - "assume:repo:hg.mozilla.org/try:*"

    # we don't create task graphs for gaia (gaia-taskcluster does that), but we do handle
    # retriggers for gaia.  For that, we use the gaia role (which is not a Mozilla tree)
    gaia:
      scopes:
        - "assume:repo:github.com/mozilla-b2g/gaia:*"

    gaia-master:
      scopes:
        - "assume:repo:github.com/mozilla-b2g/gaia:*"

    # the remainder use the defaults, and get their scopes from the corresponding role
    mozilla-b2g34_v2_1s:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/releases/mozilla-b2g34_v2_1s:*"
    mozilla-b2g44_v2_5:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/releases/mozilla-b2g44_v2_5:*"
    b2g-ota:
      scopes:
        - "assume:repo:hg.mozilla.org/releases/b2g-ota:*"
    b2g-inbound:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/integration/b2g-inbound:*"
    mozilla-inbound:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/integration/mozilla-inbound:*"
    fx-team:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/integration/fx-team:*"
    mozilla-central:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/mozilla-central:*"
    cedar:
      level: 2
      scopes:
        - "assume:repo:hg.mozilla.org/projects/cedar:*"
    cypress:
      level: 2
      scopes:
        - "assume:repo:hg.mozilla.org/projects/cypress:*"
    alder:
      level: 2
      scopes:
        - "assume:repo:hg.mozilla.org/projects/alder:*"
    pine:
      level: 2
      scopes:
        - "assume:repo:hg.mozilla.org/projects/pine:*"
